# 00. PyTorch Fyndamentals

In [2]:
import torch

In [2]:
print(torch.__version__)

2.1.2


# Intoduction to tensors

## creating


In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
# Get tensor value as Python value
scalar.item()

7

In [13]:
# vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [17]:
# Matrix
mat = torch.tensor([[1, 2], [3, 1]])
mat, mat.shape, mat.ndim

(tensor([[1, 2],
         [3, 1]]),
 torch.Size([2, 2]),
 2)

In [21]:
mat[0][0]

tensor(1)

In [27]:
# TENSOR
TENSOR = torch.tensor([[[1,2], [3,4], [5,6]]])
TENSOR, TENSOR.shape, TENSOR.ndim

(tensor([[[1, 2],
          [3, 4],
          [5, 6]]]),
 torch.Size([1, 3, 2]),
 3)

In [28]:
TENSOR[0][1][1]

tensor(4)

### RANDOM TENSORS

In [30]:
# Important because NN start with tensors full of random numbers
# recall the problem of similar tensors or 0 tensors

In [34]:
rt = torch.rand(2, 3, 4)
rt.ndim, rt.shape

(3, torch.Size([2, 3, 4]))

In [35]:
rt

tensor([[[0.2697, 0.4575, 0.7782, 0.2218],
         [0.9901, 0.1814, 0.5821, 0.1304],
         [0.7801, 0.4466, 0.2128, 0.9470]],

        [[0.9409, 0.4336, 0.9826, 0.0686],
         [0.0808, 0.2725, 0.2610, 0.0758],
         [0.3649, 0.3522, 0.0796, 0.3363]]])

In [38]:
r_image = torch.rand(size=(3, 224, 224))
r_image.ndim, r_image.shape

(3, torch.Size([3, 224, 224]))

### Zeroes and ones

In [41]:
z = torch.zeros(size=(3, 4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
o = torch.ones(size=(5,3))
o

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [46]:
e = torch.eye(3,4)
e

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [50]:
o.dtype

torch.float32

### RANGE AND LIKE

In [58]:
one_to_ten = torch.arange(start=0, end=1000, step=55)
one_to_ten

tensor([  0,  55, 110, 165, 220, 275, 330, 385, 440, 495, 550, 605, 660, 715,
        770, 825, 880, 935, 990])

In [61]:
# tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [66]:
ten_rand = torch.rand_like(input=one_to_ten, dtype=torch.float32)
ten_rand

tensor([0.0860, 0.5072, 0.8254, 0.7681, 0.7843, 0.8862, 0.9253, 0.8196, 0.4965,
        0.5354, 0.1541, 0.1224, 0.6451, 0.9409, 0.0449, 0.0928, 0.8594, 0.1423,
        0.6683])

### Tensor datatypes

In [8]:
f32_t = torch.tensor(
    [3.0, 5.0, 7.0], 
    dtype=torch.float32,
    device="cpu",
    requires_grad=False,
)

In [70]:
f32_t.dtype

torch.int16

In [72]:
f32_t.astype

tensor([3, 5, 7], dtype=torch.int16)

In [9]:
i16_t = f32_t.type(torch.int16)

In [12]:
i16_t

tensor([3, 5, 7], dtype=torch.int16)

In [14]:
f32_t * i16_t

tensor([ 9., 25., 49.])

In [15]:
f16_t = f32_t.type(torch.float16)

In [16]:
f16_t * i16_t


tensor([ 9., 25., 49.], dtype=torch.float16)

In [17]:
f16_t * f32_t


tensor([ 9., 25., 49.])

In [21]:
b_t = f32_t.type(torch.bool)
b_t

tensor([True, True, True])

In [25]:
b_t * f16_t

tensor([3., 5., 7.], dtype=torch.float16)

### Getting tensors attributes

In [27]:
# Get tensor type
f16_t.dtype

torch.float16

In [28]:
# Get tensor device
f16_t.device

device(type='cpu')

In [29]:
# Get shape
f16_t.shape

torch.Size([3])

##  MANIPULATING TENSORS

tensor operatios:
* Add
* Subs
* Mul (element wise)
* div
* matrix mul

In [39]:
# Addition
t1 = torch.tensor([1, 2, 3], dtype=torch.int)
t1 + 10

tensor([11, 12, 13], dtype=torch.int32)

In [37]:
t1 * 10

tensor([10, 20, 30])

In [41]:
t1 / 10

tensor([0, 0, 0], dtype=torch.int32)

In [42]:
t1 - 10

tensor([-9, -8, -7], dtype=torch.int32)

In [43]:
torch.mul(t1, 10)

tensor([10, 20, 30], dtype=torch.int32)

In [54]:
t1 ** 0.5

tensor([[0.5166, 0.1386, 0.6076],
        [0.7846, 0.7293, 0.6080]])

## Matrix multiplication

In [46]:
t1 = torch.rand(size=(2, 3))
t2 = torch.rand(size=(3, 2))

In [62]:
torch.mm(t1, t2)

tensor([[0.8599, 0.7753],
        [0.5339, 0.3392]], device='mps:0')

In [50]:
torch.matmul(t1, t2)

tensor([[0.3374, 0.4503],
        [0.4677, 0.6727]])

In [51]:
t1 @ t2

tensor([[0.3374, 0.4503],
        [0.4677, 0.6727]])

In [57]:
%%time
torch.matmul(t1, t2)

CPU times: user 179 µs, sys: 384 µs, total: 563 µs
Wall time: 582 µs


tensor([[0.3374, 0.4503],
        [0.4677, 0.6727]])

In [58]:
%%time
t1 @ t2

CPU times: user 35 µs, sys: 3 µs, total: 38 µs
Wall time: 40.1 µs


tensor([[0.3374, 0.4503],
        [0.4677, 0.6727]])

In [59]:
t1 = torch.rand(size=(2, 3), device='mps')
t2 = torch.rand(size=(3, 2), device='mps')

In [60]:
%%time
t1 @ t2

CPU times: user 8.04 ms, sys: 11.3 ms, total: 19.3 ms
Wall time: 123 ms


tensor([[0.8599, 0.7753],
        [0.5339, 0.3392]], device='mps:0')

In [61]:
%%time 
torch.matmul(t1, t2)

CPU times: user 828 µs, sys: 934 µs, total: 1.76 ms
Wall time: 874 µs


tensor([[0.8599, 0.7753],
        [0.5339, 0.3392]], device='mps:0')

### Tensor aggregation

In [64]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [71]:
y = torch.rand(1,3,2)
y

tensor([[[0.6744, 0.9784],
         [0.4784, 0.5272],
         [0.6465, 0.3561]]])

In [74]:
y.min(dim=1)

torch.return_types.min(
values=tensor([[0.4784, 0.3561]]),
indices=tensor([[1, 2]]))

In [75]:
torch.max(y)

tensor(0.9784)

In [86]:
torch.mean(y)
print(torch.mean(y, dim=1))
torch.mean(y, dim=2)

tensor([[0.5998, 0.6206]])


tensor([[0.8264, 0.5028, 0.5013]])

In [81]:
x.mean(dtype=torch.float32)

tensor(45.)

### Positional aggr

In [93]:
x.argmin()

tensor(0)

In [91]:
y.argmin(dim=2)

tensor([[0, 0, 1]])

In [94]:
x.argmax()

tensor(9)

In [95]:
x[9]

tensor(90)

## Reshaping, viewing and stacking

* reshaping - reshape tensor shape to a defined shape
* view - return a view of input tensor but keep the same memory
* stacking - combining tensors
* squeeze - removes all `1` dimensions
* unsqueeze - add a `1` dimension 
* permute - return a view of the input with dimensions permuted in a certain way


In [105]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [106]:
x_reshaped = x.reshape(2, 6)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [109]:
x_reshaped = x.reshape(-1, 2, 2)
x_reshaped

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [111]:
# Change the view
z = x.view(1, 12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [113]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [119]:
# Stack tensors
s = torch.stack((x, x.view(12)))
s[0][0] = -1
s

tensor([[-1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [122]:
s = torch.vstack((x, x))
s

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [123]:
s = torch.hstack((x, x))
s

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  5.,  2.,
         3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [126]:
# Squeeze
x_reshaped = x.reshape(shape=(1, -1))
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [11]:
x_squeezed =  .squeeze()
x_squeezed

NameError: name 'x_reshaped' is not defined

In [133]:
# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

In [141]:
# torch.permute
r = torch.rand(224, 224, 3)
r.shape

torch.Size([224, 224, 3])

In [146]:
# torch.permute(r, dims=(2,0,1)).shape
# it's a VIEW!!!
r.permute(dims=(2,0,1)).shape


torch.Size([3, 224, 224])

### SELECTING FROM TENSORS

In [149]:
x = torch.arange(1, 13).reshape(2, 3, -1)
x

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [155]:
x[:, :, 0]

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [157]:
x[-1, -1, -1]

tensor(12)

#### PyTorch and NumPy

In [159]:
import torch
import numpy as np

In [165]:
arr = np.array([1,2,3,4,5])
t_arr = torch.from_numpy(arr)

t_arr

tensor([1, 2, 3, 4, 5])

In [169]:
t = torch.rand((2, 3))
n = t.numpy()
n

array([[0.5608825 , 0.03161216, 0.8100872 ],
       [0.0625031 , 0.8713674 , 0.04697299]], dtype=float32)

### Reproducibility

In [2]:
import torch

rA = torch.rand(3, 4)
rB = torch.rand(3, 4)

print(rA)
print(rB)
rA == rB

tensor([[0.1370, 0.6912, 0.4895, 0.0322],
        [0.5152, 0.5199, 0.9240, 0.9503],
        [0.0479, 0.7727, 0.6035, 0.1160]])
tensor([[0.1328, 0.6161, 0.3455, 0.5489],
        [0.1566, 0.6423, 0.9854, 0.0425],
        [0.2693, 0.7291, 0.2840, 0.0706]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [3]:
# Random on each call is different, but for every rerun it's same!
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

rA = torch.rand(3, 4)
rB = torch.rand(3, 4)

print(rA)
print(rB)
rA == rB

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [5]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rA = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
rB = torch.rand(3, 4)

print(rA)
print(rB)
rA == rB

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [10]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rA = torch.rand(3, 4)
rB = torch.rand(3, 4)

print(rA)
print(rB)
rA == rB

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

## GPUs and CPUs

In [215]:
import torch
torch.mps

<module 'torch.mps' from '/Users/pavelmikheev/miniconda3/envs/torch/lib/python3.10/site-packages/torch/mps/__init__.py'>

In [220]:
t1 = torch.rand(3, 4)
t2 = torch.rand(4, 6)

In [221]:
%%time
torch.matmul(t1, t2)

CPU times: user 111 µs, sys: 29 µs, total: 140 µs
Wall time: 135 µs


tensor([[1.1802, 0.9905, 0.7506, 1.1640, 1.7959, 0.8913],
        [1.1031, 0.8661, 0.6680, 1.0827, 1.7386, 0.8244],
        [1.3308, 0.8868, 0.7307, 1.2280, 1.5189, 0.8096]])

In [222]:
t3 = t1.to('mps')
t4 = t2.to('mps')

In [224]:
%%time
torch.matmul(t3 , t4)

CPU times: user 840 µs, sys: 833 µs, total: 1.67 ms
Wall time: 697 µs


tensor([[1.1802, 0.9905, 0.7506, 1.1640, 1.7959, 0.8913],
        [1.1031, 0.8661, 0.6680, 1.0827, 1.7386, 0.8244],
        [1.3308, 0.8868, 0.7307, 1.2280, 1.5189, 0.8096]], device='mps:0')

In [226]:
# MOVING BACK TO CPU

t3.cpu().numpy()

array([[0.7672256 , 0.6757198 , 0.66247797, 0.2296769 ],
       [0.95447576, 0.6098752 , 0.56432   , 0.0593726 ],
       [0.70989424, 0.4249897 , 0.27093786, 0.9294733 ]], dtype=float32)